### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by danny007in** [bangkitdev/astro-html-beautifier#1]
```

 error   ENOENT: no such file or directory, scandir '/C:/Users/Daniel/Documents/AdminLTE/dist/pages/'
  File:
    C:\Users\Daniel\Documents\AdminLTE\node_modules\astro-html-beautifier\dist\index.mjs:27:22
  Code:
    26 | const getAllFiles = function (dirPath, arrayOfFiles = []) {
    > 27 |     const files = fs.readdirSync(dirPath);
         |                      ^
      28 |     files.forEach(function (file) {
      29 |         if (fs.statSync(dirPath + "/" + file).isDirectory()) {
      30 |             arrayOfFiles = getAllFiles(dirPath + "/" + file, arrayOfFiles);
  Stacktrace:
Error: ENOENT: no such file or directory, scandir '/C:/Users/Daniel/Documents/AdminLTE/dist/pages/'
    at Object.readdirSync (node:fs:1452:3)
    at getAllFiles (file:///C:/Users/Daniel/Documents/AdminLTE/node_modules/astro-html-beautifier/dist/index.mjs:27:22)
    at astro:build:done (file:///C:/Users/Daniel/Documents/AdminLTE/node_modules/astro-html-beautifier/dist/index.mjs:69:34)
    at runHookBuildDone (file:///C:/Users/Daniel/Documents/AdminLTE/node_modules/astro/dist/integrations/index.js:249:58)
    at async AstroBuilder.build (file:///C:/Users/Daniel/Documents/AdminLTE/node_modules/astro/dist/core/build/index.js:135:5)
    at async AstroBuilder.run (file:///C:/Users/Daniel/Documents/AdminLTE/node_modules/astro/dist/core/build/index.js:156:7)
    at async build (file:///C:/Users/Daniel/Documents/AdminLTE/node_modules/astro/dist/core/build/index.js:37:3)
    at async runCommand (file:///C:/Users/Daniel/Documents/AdminLTE/node_modules/astro/dist/cli/index.js:167:14)
    at async cli (file:///C:/Users/Daniel/Documents/AdminLTE/node_modules/astro/dist/cli/index.js:209:5)

ERROR: "docs-compile" exited with 1.
```

Astro Version
```
"astro": "^2.3.3",
```

Node.js version: 18

**Comment by cizen-otsuki** [comment]
Hello.
I made this modification and it worked fine.

astro  v2.7.1

```
import path from "path";
import fs from "fs";
import chalk from "chalk";
import beautify from "js-beautify";
import { globSync } from 'glob';

const defaultConfig = {
    indent_size: 4,
    indent_char: "\t",
    max_preserve_newlines: -1,
    preserve_newlines: false,
    keep_array_indentation: false,
    break_chained_methods: false,
    indent_scripts: "keep",
    brace_style: "collapse",
    space_before_conditional: false,
    unescape_strings: false,
    jslint_happy: false,
    end_with_newline: false,
    wrap_line_length: 0,
    indent_inner_html: false,
    comma_first: false,
    e4x: false,
    indent_empty_lines: false,
};

/*const getAllFiles = function (dirPath, arrayOfFiles = []) {
    const files = fs.readdirSync(dirPath);
    files.forEach(function (file) {
        if (fs.statSync(dirPath + "/" + file).isDirectory()) {
            arrayOfFiles = getAllFiles(dirPath + "/" + file, arrayOfFiles);
        } else {
            arrayOfFiles.push(path.join(dirPath, "/", file));
        }
    });

    return arrayOfFiles;
};*/

const htmlFormatter = (filePath, options) => {
    let data;
    try {
        data = fs.readFileSync(filePath, { encoding: "utf8" });
        let result = beautify.html(data, options);
        fs.writeFileSync(filePath, result);
        let rootDir = path.basename(path.dirname(filePath));
        rootDir === "dist" ? (rootDir = "") : (rootDir = rootDir + "/");
        console.log(
            chalk.green(
                `${rootDir}${path.basename(filePath)} ${chalk.white.dim(
                    "Beautified!"
                )}`
            )
        );
    } catch (err) {
        if (err.code === "ENOENT") {
            console.log(chalk.red.bold(filePath));
            console.log(chalk.grey.dim("File not found!"));
        } else {
            throw err;
        }
    }
};

function htmlBeautify (options = { ...defaultConfig }) {
    return {
        name: "astro-html-beautifier",
        hooks: {
            "astro:build:done": async ({ dir }) => {
                //const allFiles = getAllFiles(dir.pathname);
                globSync(`${dir.pathname}**/*.html`).forEach((filePath) => {
                    // const ext = path.extname(filePath);
                    // if (ext === ".html") {
                        htmlFormatter(filePath, options);
                    // }
                });
                console.log("");
            },
        },
    };
}

export default function () {
    return {
        name: 'astro-html-beautifier',
        hooks: {
            'astro:config:setup': ({ updateConfig }) => {
                updateConfig({
                    integrations: [htmlBeautify()],
                });
            },
        },
    };
}

**Comment by danny007in** [comment]
@cizen-otsuki Better you can create PR for it
